Repository Spring-io-2024-modulith-workshop/conference-kata-implementation-modulith, pull requests merged in 2024-05, with the labels that each got.

#28 Voting system
  README.md
  documentation/votes.http
  pom.xml
  src/main/java/com/acme/conferencesystem/cfp_proposals/ProposalInternalAPI.java
  src/main/java/com/acme/conferencesystem/cfp_proposals/business/Proposal.java
  src/main/java/com/acme/conferencesystem/cfp_proposals/business/ProposalService.java
  src/main/java/com/acme/conferencesystem/cfp_proposals/business/ProposalStatus.java
  src/main/java/com/acme/conferencesystem/cfp_proposals/http/ProposalController.java
  src/main/java/com/acme/conferencesystem/cfp_proposals/persistence/ProposalEntity.java
  src/main/java/com/acme/conferencesystem/ticket/business/TicketService.java
  src/main/java/com/acme/conferencesystem/users/UserInternalAPI.java
  src/main/java/com/acme/conferencesystem/users/business/UserService.java
  src/main/java/com/acme/conferencesystem/voting/business/Vote.java
  src/main/java/com/acme/conferencesystem/voting/business/VoteMapper.java
  src/main/java/com/acme/conferencesystem/voting/business/VoteService.java
  src/main/java/com/acme/conferencesystem/voting/http/VoteController.java
  src/main/java/com/acme/conferencesystem/voting/persistence/VoteEntity.java
  src/main/java/com/acme/conferencesystem/voting/persistence/VoteRepository.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__create_users_schema.sql
  src/main/resources/db/migration/V2__create_proposals_schema.sql
  src/main/resources/db/migration/V3__create_tickets_schema.sql
  src/main/resources/db/migration/V4__create_votes_schema.sql
  src/main/resources/db/migration/V5__initial_data.sql
  src/main/resources/sql/schema/1-proposals.sql
  src/test/java/com/acme/conferencesystem/ArchitectureTests.java
  src/test/java/com/acme/conferencesystem/ContainerConfig.java
  src/test/java/com/acme/conferencesystem/cfp_proposals/business/ProposalServiceTest.java
  src/test/java/com/acme/conferencesystem/cfp_proposals/http/ProposalControllerIntegrationTest.java
  src/test/java/com/acme/conferencesystem/ticket/business/TicketServiceTest.java
  src/test/java/com/acme/conferencesystem/ticket/http/TicketControllerIntegrationTest.java
  src/test/java/com/acme/conferencesystem/users/business/UserServiceTest.java
  src/test/java/com/acme/conferencesystem/users/http/UserControllerIntegrationTest.java
  src/test/java/com/acme/conferencesystem/voting/business/VoteServiceTest.java
  src/test/java/com/acme/conferencesystem/voting/http/VoteControllerIntegrationTest.java
  src/test/java/com/acme/conferencesystem/voting/persistence/VoteRepositoryTest.java
Labels: enhancement

#30 fix: improve code
  .mvn/jvm.config
  pom.xml
  src/main/java/com/acme/conferencesystem/cfp_proposals/ProposalInternalAPI.java
  src/main/java/com/acme/conferencesystem/cfp_proposals/business/ProposalService.java
  src/main/java/com/acme/conferencesystem/cfp_proposals/http/ProposalController.java
  src/main/java/com/acme/conferencesystem/cfp_proposals/persistence/ProposalEntity.java
  src/main/java/com/acme/conferencesystem/ticket/business/TicketService.java
  src/main/java/com/acme/conferencesystem/ticket/persistence/TicketEntity.java
  src/main/resources/db/migration/V6__include_date_modification_column.sql
  src/test/java/com/acme/conferencesystem/cfp_proposals/business/ProposalServiceTest.java
  src/test/java/com/acme/conferencesystem/users/http/UserControllerIntegrationTest.java
Labels: enhancement

#33 improve documentation
  README.md
Labels: documentation, enhancement

#35 fix: improve factory methods
  src/main/java/com/acme/conferencesystem/cfp_proposals/business/ProposalService.java
  src/main/java/com/acme/conferencesystem/cfp_proposals/persistence/ProposalEntity.java
  src/main/java/com/acme/conferencesystem/ticket/business/TicketService.java
  src/main/java/com/acme/conferencesystem/ticket/persistence/TicketEntity.java
  src/main/java/com/acme/conferencesystem/users/business/UserService.java
  src/main/java/com/acme/conferencesystem/voting/business/VoteService.java
Labels: enhancement

#46 fix: Static local test configuration
  src/test/java/com/acme/conferencesystem/TestApplication.java
Labels: bug

#53 chore: update to flyway 10.13.0
  pom.xml
Labels: chore
